-- StockScout-EOD v1 public scan index and owner-scoped application state.
--
-- This migration is deliberately additive. It does not replace the existing
-- StockScout full_scan, stockscout_next, alert, or OAuth objects in the live
-- project. GitHub publishing reaches the write-only RPCs below exclusively
-- through the OIDC-verifying Edge Function.

create extension if not exists pgcrypto with schema extensions;

create schema if not exists stockscout_private;
-- Do not change existing schema grants: the live MCP already has private
-- StockScout objects here. Object-level grants below keep this migration
-- additive. USAGE alone exposes no table or function.
grant usage on schema stockscout_private to authenticated, service_role;

create table public.eod_scans (
  id bigint generated by default as identity primary key,
  run_id text not null unique check (run_id ~ '^[A-Za-z0-9._:-]{1,100}$'),
  scan_date date not null,
  market_data_date date not null,
  schema_version text not null check (schema_version = 'stockscout-eod/v1'),
  health_status text not null check (health_status in ('healthy', 'degraded')),
  candidate_count integer not null check (candidate_count >= 0),
  excluded_count integer not null check (excluded_count >= 0),
  record_count integer not null check (
    record_count >= 0 and record_count = candidate_count + excluded_count
  ),
  records_hash text not null check (records_hash ~ '^[0-9a-f]{64}$'),
  manifest_hash text not null check (manifest_hash ~ '^[0-9a-f]{64}$'),
  ranking_version text,
  detector_version text,
  health_details jsonb not null default '{}'::jsonb
    check (jsonb_typeof(health_details) = 'object'),
  provenance jsonb not null default '{}'::jsonb
    check (jsonb_typeof(provenance) = 'object'),
  asset_hashes jsonb not null default '{}'::jsonb
    check (jsonb_typeof(asset_hashes) = 'object'),
  published_at timestamptz not null default now()
);

create table public.eod_scan_state (
  singleton boolean primary key default true check (singleton),
  active_scan_id bigint not null references public.eod_scans(id) on delete restrict,
  updated_at timestamptz not null default now()
);

create table public.eod_candidates (
  scan_id bigint not null references public.eod_scans(id) on delete cascade,
  document_id text not null unique,
  ticker text not null check (ticker ~ '^[A-Z0-9._-]{1,20}$'),
  source text not null check (source in ('candidate', 'excluded')),
  scan_order integer not null check (scan_order >= 0),
  trade_status text,
  primary_setup text,
  risk_level text,
  scan_price numeric,
  entry_risk_pct numeric,
  ranking_score numeric,
  record jsonb not null check (jsonb_typeof(record) = 'object'),
  search_document tsvector not null,
  record_hash text not null check (record_hash ~ '^[0-9a-f]{64}$'),
  primary key (scan_id, ticker)
);

create table public.eod_candidate_history (
  scan_id bigint not null references public.eod_scans(id) on delete cascade,
  ticker text not null check (ticker ~ '^[A-Z0-9._-]{1,20}$'),
  source text not null check (source in ('candidate', 'excluded')),
  scan_order integer not null check (scan_order >= 0),
  trade_status text,
  primary_setup text,
  risk_level text,
  scan_price numeric,
  entry_risk_pct numeric,
  ranking_score numeric,
  summary jsonb not null default '{}'::jsonb
    check (jsonb_typeof(summary) = 'object'),
  primary key (scan_id, ticker)
);

create table public.eod_scan_fields (
  scan_id bigint not null references public.eod_scans(id) on delete cascade,
  field_path text not null
    check (field_path ~ '^[A-Za-z0-9_-]+(\.[A-Za-z0-9_-]+)*$'),
  scalar_types text[] not null default '{}',
  populated_count integer not null default 0 check (populated_count >= 0),
  example jsonb,
  primary key (scan_id, field_path)
);

-- Private staging is never exposed to browser roles. It exists only long
-- enough to make begin/chunk/finalize resumable and the activation atomic.
create table stockscout_private.eod_publish_uploads (
  id uuid primary key default gen_random_uuid(),
  run_id text not null check (run_id ~ '^[A-Za-z0-9._:-]{1,100}$'),
  expected_count integer not null check (expected_count between 1 and 100000),
  expected_records_hash text not null check (expected_records_hash ~ '^[0-9a-f]{64}$'),
  manifest_hash text not null check (manifest_hash ~ '^[0-9a-f]{64}$'),
  manifest jsonb not null check (jsonb_typeof(manifest) = 'object'),
  status text not null default 'uploading'
    check (status in ('uploading', 'finalizing', 'failed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (run_id, manifest_hash)
);

create table stockscout_private.eod_publish_records (
  upload_id uuid not null
    references stockscout_private.eod_publish_uploads(id) on delete cascade,
  chunk_index integer not null check (chunk_index >= 0),
  ticker text not null check (ticker ~ '^[A-Z0-9._-]{1,20}$'),
  source text not null check (source in ('candidate', 'excluded')),
  scan_order integer not null check (scan_order >= 0),
  record_hash text not null check (record_hash ~ '^[0-9a-f]{64}$'),
  record jsonb not null check (jsonb_typeof(record) = 'object'),
  summary jsonb not null default '{}'::jsonb
    check (jsonb_typeof(summary) = 'object'),
  primary key (upload_id, ticker)
);

-- Authentication alone is not authorization. Only explicitly allowlisted
-- Supabase users may use owner state or private chart payloads, even if a
-- future Auth configuration accidentally permits another signup.
create table stockscout_private.eod_owners (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

-- Reuse the single owner already proven by the private full-scan index. A
-- surprising multi-owner project aborts instead of silently broadening access;
-- a fresh project with no legacy table remains empty until explicitly seeded.
do $block$
declare
  v_owner_count integer;
  v_owner_id uuid;
begin
  if to_regclass('stockscout_private.full_scan_snapshots') is not null then
    execute
      'select count(distinct owner_id) from stockscout_private.full_scan_snapshots'
      into v_owner_count;
    if v_owner_count > 1 then
      raise exception
        'refusing to seed eod_owners: legacy full scan has % owners',
        v_owner_count;
    elsif v_owner_count = 1 then
      execute
        'select owner_id from stockscout_private.full_scan_snapshots limit 1'
        into v_owner_id;
      insert into stockscout_private.eod_owners (user_id)
      values (v_owner_id)
      on conflict (user_id) do nothing;
    end if;
  end if;
end;
$block$;

-- Owner state is namespaced to coexist with the current stockscout_next
-- drawing/alert tables during the parallel-run and rollback window.
create table public.eod_watchlists (
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null default 'Default' check (length(name) between 1 and 80),
  ticker text not null check (ticker ~ '^[A-Z0-9._-]{1,20}$'),
  notes text check (notes is null or length(notes) <= 1000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, name, ticker)
);

create table public.eod_saved_screens (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (length(name) between 1 and 80),
  definition jsonb not null check (jsonb_typeof(definition) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, name)
);

create table public.eod_drawings (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  ticker text not null check (ticker ~ '^[A-Z0-9._-]{1,20}$'),
  interval text not null check (length(interval) between 1 and 20),
  payload jsonb not null check (jsonb_typeof(payload) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.eod_alerts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (length(name) between 1 and 120),
  ticker text check (ticker is null or ticker ~ '^[A-Z0-9._-]{1,20}$'),
  payload jsonb not null check (jsonb_typeof(payload) = 'object'),
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.eod_alert_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  alert_id uuid not null references public.eod_alerts(id) on delete cascade,
  run_id text not null check (run_id ~ '^[A-Za-z0-9._:-]{1,100}$'),
  event_key text not null check (length(event_key) between 1 and 200),
  payload jsonb not null check (jsonb_typeof(payload) = 'object'),
  created_at timestamptz not null default now(),
  delivered_at timestamptz,
  read_at timestamptz,
  unique (user_id, event_key)
);

create table public.eod_delivery_state (
  user_id uuid not null references auth.users(id) on delete cascade,
  channel text not null check (channel in ('telegram', 'email', 'push')),
  digest_key text not null check (
    digest_key ~ '^(daily|operational_error):[0-9]{4}-[0-9]{2}-[0-9]{2}$'
  ),
  content_hash text not null check (content_hash ~ '^[0-9a-f]{64}$'),
  total_parts integer not null check (total_parts > 0),
  last_successful_part integer not null default 0
    check (last_successful_part >= 0 and last_successful_part <= total_parts),
  completed_at timestamptz,
  payload jsonb not null default '{}'::jsonb
    check (jsonb_typeof(payload) = 'object'),
  updated_at timestamptz not null default now(),
  primary key (user_id, channel, digest_key)
);

create index eod_scans_date_idx
  on public.eod_scans (scan_date desc, published_at desc);
create index eod_candidates_order_idx
  on public.eod_candidates (scan_id, source, scan_order);
create index eod_candidates_screen_idx
  on public.eod_candidates (scan_id, trade_status, primary_setup, entry_risk_pct);
create index eod_candidates_record_gin
  on public.eod_candidates using gin (record jsonb_path_ops);
create index eod_candidates_search_gin
  on public.eod_candidates using gin (search_document);
create index eod_history_ticker_scan_idx
  on public.eod_candidate_history (ticker, scan_id);
create index eod_history_scan_order_idx
  on public.eod_candidate_history (scan_id, source, scan_order);
create index eod_history_setup_idx
  on public.eod_candidate_history (scan_id, trade_status, primary_setup);
create index eod_publish_uploads_age_idx
  on stockscout_private.eod_publish_uploads (created_at);
create index eod_saved_screens_user_idx
  on public.eod_saved_screens (user_id);
create index eod_drawings_user_ticker_idx
  on public.eod_drawings (user_id, ticker, interval);
create index eod_alerts_user_enabled_idx
  on public.eod_alerts (user_id, enabled);
create index eod_alert_events_alert_idx
  on public.eod_alert_events (alert_id);
create index eod_alert_events_user_created_idx
  on public.eod_alert_events (user_id, created_at desc);

alter table public.eod_scans enable row level security;
alter table public.eod_scan_state enable row level security;
alter table public.eod_candidates enable row level security;
alter table public.eod_candidate_history enable row level security;
alter table public.eod_scan_fields enable row level security;
alter table stockscout_private.eod_publish_uploads enable row level security;
alter table stockscout_private.eod_publish_records enable row level security;
alter table stockscout_private.eod_owners enable row level security;
alter table public.eod_watchlists enable row level security;
alter table public.eod_saved_screens enable row level security;
alter table public.eod_drawings enable row level security;
alter table public.eod_alerts enable row level security;
alter table public.eod_alert_events enable row level security;
alter table public.eod_delivery_state enable row level security;

create or replace function stockscout_private.eod_is_owner()
returns boolean
language sql
stable
security definer
set search_path = ''
as $function$
  select
    (select auth.uid()) is not null
    and exists (
      select 1
      from stockscout_private.eod_owners o
      where o.user_id = (select auth.uid())
    );
$function$;

revoke all on function stockscout_private.eod_is_owner()
  from public, anon, authenticated, service_role;
grant execute on function stockscout_private.eod_is_owner()
  to authenticated, service_role;

-- Trusted publishers derive the one allowlisted owner from database state.
-- This avoids another long-lived owner identifier in Edge/GitHub configuration
-- and fails closed if project ownership ever becomes ambiguous.
create or replace function public.eod_single_owner_id()
returns uuid
language plpgsql
stable
security definer
set search_path = ''
as $function$
declare
  v_count integer;
  v_owner_id uuid;
begin
  select count(*), max(user_id::text)::uuid
  into v_count, v_owner_id
  from stockscout_private.eod_owners;
  if v_count <> 1 or v_owner_id is null then
    raise exception 'StockScout-EOD requires exactly one allowlisted owner'
      using errcode = '42501';
  end if;
  return v_owner_id;
end;
$function$;

revoke all on function public.eod_single_owner_id()
  from public, anon, authenticated, service_role;
grant execute on function public.eod_single_owner_id() to service_role;

create policy eod_scans_public_read on public.eod_scans
  for select to anon, authenticated using (true);
create policy eod_scan_state_public_read on public.eod_scan_state
  for select to anon, authenticated using (true);
create policy eod_candidates_public_read on public.eod_candidates
  for select to anon, authenticated using (true);
create policy eod_candidate_history_public_read on public.eod_candidate_history
  for select to anon, authenticated using (true);
create policy eod_scan_fields_public_read on public.eod_scan_fields
  for select to anon, authenticated using (true);

create policy eod_watchlists_owner_select on public.eod_watchlists
  for select to authenticated
  using (
    (select stockscout_private.eod_is_owner())
    and (select auth.uid()) = user_id
  );
create policy eod_watchlists_owner_insert on public.eod_watchlists
  for insert to authenticated
  with check (
    (select stockscout_private.eod_is_owner())
    and (select auth.uid()) = user_id
  );
create policy eod_watchlists_owner_update on public.eod_watchlists
  for update to authenticated
  using (
    (select stockscout_private.eod_is_owner())
    and (select auth.uid()) = user_id
  )
  with check (
    (select stockscout_private.eod_is_owner())
    and (select auth.uid()) = user_id
  );
create policy eod_watchlists_owner_delete on public.eod_watchlists
  for delete to authenticated
  using (
    (select stockscout_private.eod_is_owner())
    and (select auth.uid()) = user_id
  );

create policy eod_saved_screens_owner_select on public.eod_saved_screens
  for select to authenticated
  using (
    (select stockscout_private.eod_is_owner())
    and (select auth.uid()) = user_id
  );
create policy eod_saved_screens_owner_insert on public.eod_saved_screens
  for insert to authenticated
  with check (
    (select stockscout_private.eod_is_owner())
    and (select auth.uid()) = user_id
  );
create policy eod_saved_screens_owner_update on public.eod_saved_screens
  for update to authenticated
  using (
    (select stockscout_private.eod_is_owner())
    and (select auth.uid()) = user_id
  )
  with check (
    (select stockscout_private.eod_is_owner())
    and (select auth.uid()) = user_id
  );
create policy eod_saved_screens_owner_delete on public.eod_saved_screens
  for delete to authenticated
  using (
    (select stockscout_private.eod_is_owner())
    and (select auth.uid()) = user_id
  );

create policy eod_drawings_owner_select on public.eod_drawings
  for select to authenticated
  using (
    (select stockscout_private.eod_is_owner())
    and (select auth.uid()) = user_id
  );
create policy eod_drawings_owner_insert on public.eod_drawings
  for insert to authenticated
  with check (
    (select stockscout_private.eod_is_owner())
    and (select auth.uid()) = user_id
  );
create policy eod_drawings_owner_update on public.eod_drawings
  for update to authenticated
  using (
    (select stockscout_private.eod_is_owner())
    and (select auth.uid()) = user_id
  )
  with check (
    (select stockscout_private.eod_is_owner())
    and (select auth.uid()) = user_id
  );
create policy eod_drawings_owner_delete on public.eod_drawings
  for delete to authenticated
  using (
    (select stockscout_private.eod_is_owner())
    and (select auth.uid()) = user_id
  );

create policy eod_alerts_owner_select on public.eod_alerts
  for select to authenticated
  using (
    (select stockscout_private.eod_is_owner())
    and (select auth.uid()) = user_id
  );
create policy eod_alerts_owner_insert on public.eod_alerts
  for insert to authenticated
  with check (
    (select stockscout_private.eod_is_owner())
    and (select auth.uid()) = user_id
  );
create policy eod_alerts_owner_update on public.eod_alerts
  for update to authenticated
  using (
    (select stockscout_private.eod_is_owner())
    and (select auth.uid()) = user_id
  )
  with check (
    (select stockscout_private.eod_is_owner())
    and (select auth.uid()) = user_id
  );
create policy eod_alerts_owner_delete on public.eod_alerts
  for delete to authenticated
  using (
    (select stockscout_private.eod_is_owner())
    and (select auth.uid()) = user_id
  );

create policy eod_alert_events_owner_select on public.eod_alert_events
  for select to authenticated
  using (
    (select stockscout_private.eod_is_owner())
    and (select auth.uid()) = user_id
  );
create policy eod_alert_events_owner_mark_read on public.eod_alert_events
  for update to authenticated
  using (
    (select stockscout_private.eod_is_owner())
    and (select auth.uid()) = user_id
  )
  with check (
    (select stockscout_private.eod_is_owner())
    and (select auth.uid()) = user_id
  );

create policy eod_delivery_state_owner_select on public.eod_delivery_state
  for select to authenticated
  using (
    (select stockscout_private.eod_is_owner())
    and (select auth.uid()) = user_id
  );

-- Keep grants explicit even on projects that still auto-expose public tables.
revoke all on table
  public.eod_scans,
  public.eod_scan_state,
  public.eod_candidates,
  public.eod_candidate_history,
  public.eod_scan_fields,
  public.eod_watchlists,
  public.eod_saved_screens,
  public.eod_drawings,
  public.eod_alerts,
  public.eod_alert_events,
  public.eod_delivery_state
from public, anon, authenticated, service_role;

grant select on table
  public.eod_scans,
  public.eod_scan_state,
  public.eod_candidates,
  public.eod_candidate_history,
  public.eod_scan_fields
to anon, authenticated, service_role;

grant select, insert, update, delete on table
  public.eod_watchlists,
  public.eod_saved_screens,
  public.eod_drawings,
  public.eod_alerts
to authenticated;
grant select on table public.eod_alert_events, public.eod_delivery_state
  to authenticated;
grant update (read_at) on table public.eod_alert_events to authenticated;

grant select, insert, update, delete on table
  public.eod_watchlists,
  public.eod_saved_screens,
  public.eod_drawings,
  public.eod_alerts,
  public.eod_alert_events,
  public.eod_delivery_state
to service_role;

revoke all on table
  stockscout_private.eod_publish_uploads,
  stockscout_private.eod_publish_records,
  stockscout_private.eod_owners
from public, anon, authenticated;
grant select, insert, update, delete on table
  stockscout_private.eod_publish_uploads,
  stockscout_private.eod_publish_records,
  stockscout_private.eod_owners
to service_role;

grant usage, select on sequence public.eod_scans_id_seq,
  public.eod_alert_events_id_seq to service_role;

create or replace function stockscout_private.eod_set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $function$
begin
  new.updated_at := now();
  return new;
end;
$function$;

create trigger eod_watchlists_set_updated_at
before update on public.eod_watchlists
for each row execute function stockscout_private.eod_set_updated_at();
create trigger eod_saved_screens_set_updated_at
before update on public.eod_saved_screens
for each row execute function stockscout_private.eod_set_updated_at();
create trigger eod_drawings_set_updated_at
before update on public.eod_drawings
for each row execute function stockscout_private.eod_set_updated_at();
create trigger eod_alerts_set_updated_at
before update on public.eod_alerts
for each row execute function stockscout_private.eod_set_updated_at();
create trigger eod_delivery_state_set_updated_at
before update on public.eod_delivery_state
for each row execute function stockscout_private.eod_set_updated_at();

revoke all on function stockscout_private.eod_set_updated_at() from public,
  anon, authenticated, service_role;

create or replace function public.eod_begin_publish(p_manifest jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_upload_id uuid;
  v_candidate_count integer;
  v_excluded_count integer;
  v_record_count integer;
begin
  if jsonb_typeof(p_manifest) <> 'object'
     or coalesce(p_manifest->>'schemaVersion', '') <> 'stockscout-eod/v1'
     or coalesce(p_manifest->>'runId', '') !~ '^[A-Za-z0-9._:-]{1,100}$'
     or coalesce(p_manifest->>'scanDate', '') !~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
     or coalesce(p_manifest->>'marketDataDate', '') !~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
     or coalesce(p_manifest#>>'{health,status}', '') <> 'healthy'
     or coalesce(p_manifest#>>'{counts,candidates}', '') !~ '^[0-9]+$'
     or coalesce(p_manifest#>>'{counts,excluded}', '') !~ '^[0-9]+$'
     or coalesce(p_manifest#>>'{counts,total}', '') !~ '^[0-9]+$'
     or coalesce(p_manifest->>'recordsHash', '') !~ '^[0-9a-f]{64}$'
     or coalesce(p_manifest->>'manifestHash', '') !~ '^[0-9a-f]{64}$'
     or jsonb_typeof(coalesce(p_manifest->'assetHashes', '{}'::jsonb)) <> 'object'
     or jsonb_typeof(coalesce(p_manifest->'provenance', '{}'::jsonb)) <> 'object'
     or jsonb_typeof(coalesce(p_manifest->'fieldCatalog', '[]'::jsonb)) <> 'array'
  then
    raise exception 'invalid StockScout-EOD publish manifest'
      using errcode = '22023';
  end if;

  v_candidate_count := (p_manifest#>>'{counts,candidates}')::integer;
  v_excluded_count := (p_manifest#>>'{counts,excluded}')::integer;
  v_record_count := (p_manifest#>>'{counts,total}')::integer;
  if v_record_count < 1 or v_record_count > 100000
     or v_record_count <> v_candidate_count + v_excluded_count then
    raise exception 'manifest counts do not reconcile' using errcode = '22023';
  end if;

  delete from stockscout_private.eod_publish_uploads
  where created_at < now() - interval '24 hours';

  insert into stockscout_private.eod_publish_uploads (
    run_id, expected_count, expected_records_hash, manifest_hash, manifest
  ) values (
    p_manifest->>'runId', v_record_count, p_manifest->>'recordsHash',
    p_manifest->>'manifestHash', p_manifest
  )
  on conflict (run_id, manifest_hash) do update set
    expected_count = excluded.expected_count,
    expected_records_hash = excluded.expected_records_hash,
    manifest = excluded.manifest,
    status = 'uploading',
    updated_at = now()
  returning id into v_upload_id;

  -- A repeated begin starts a deterministic retry of the same immutable
  -- upload.  Clear partial rows while holding the upload row lock acquired by
  -- the upsert; append/finalize take the same lock, so stale wrapper metadata
  -- (especially scan_order or summary) cannot survive into a retry.
  delete from stockscout_private.eod_publish_records
  where upload_id = v_upload_id;

  return jsonb_build_object(
    'uploadId', v_upload_id,
    'runId', p_manifest->>'runId',
    'expectedCount', v_record_count
  );
end;
$function$;

create or replace function public.eod_append_publish_chunk(
  p_upload_id uuid,
  p_chunk_index integer,
  p_records jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_received_count integer;
begin
  if p_chunk_index < 0
     or jsonb_typeof(p_records) <> 'array'
     or jsonb_array_length(p_records) < 1
     or jsonb_array_length(p_records) > 100 then
    raise exception 'invalid publish chunk' using errcode = '22023';
  end if;

  perform 1
  from stockscout_private.eod_publish_uploads
  where id = p_upload_id and status = 'uploading'
  for update;
  if not found then
    raise exception 'publish upload is missing or not writable'
      using errcode = '22023';
  end if;

  if exists (
    select 1
    from jsonb_array_elements(p_records) as r
    where coalesce(r->>'ticker', '') !~ '^[A-Z0-9._-]{1,20}$'
       or coalesce(r->>'source', '') not in ('candidate', 'excluded')
       or coalesce(r->>'scanOrder', '') !~ '^[0-9]+$'
       or coalesce(r->>'recordHash', '') !~ '^[0-9a-f]{64}$'
       or jsonb_typeof(r->'record') <> 'object'
       or jsonb_typeof(coalesce(r->'summary', '{}'::jsonb)) <> 'object'
  ) then
    raise exception 'invalid publish record' using errcode = '22023';
  end if;

  insert into stockscout_private.eod_publish_records (
    upload_id, chunk_index, ticker, source, scan_order,
    record_hash, record, summary
  )
  select
    p_upload_id,
    p_chunk_index,
    r->>'ticker',
    r->>'source',
    (r->>'scanOrder')::integer,
    r->>'recordHash',
    r->'record',
    coalesce(r->'summary', '{}'::jsonb)
  from jsonb_array_elements(p_records) as r
  on conflict (upload_id, ticker) do update set
    chunk_index = excluded.chunk_index,
    source = excluded.source,
    scan_order = excluded.scan_order,
    record_hash = excluded.record_hash,
    record = excluded.record,
    summary = excluded.summary;

  update stockscout_private.eod_publish_uploads
  set updated_at = now()
  where id = p_upload_id;

  select count(*) into v_received_count
  from stockscout_private.eod_publish_records
  where upload_id = p_upload_id;

  return jsonb_build_object(
    'uploadId', p_upload_id,
    'receivedCount', v_received_count
  );
end;
$function$;

create or replace function public.eod_finalize_publish(p_upload_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_upload stockscout_private.eod_publish_uploads%rowtype;
  v_count integer;
  v_hash text;
  v_scan_id bigint;
  v_existing_scan_id bigint;
  v_existing_hash text;
  v_previous_run_id text;
begin
  select * into v_upload
  from stockscout_private.eod_publish_uploads
  where id = p_upload_id
  for update;
  if not found then
    raise exception 'publish upload not found' using errcode = '22023';
  end if;

  select
    count(*),
    encode(
      extensions.digest(
        -- record_hash is the JCS-compatible SHA-256 of the complete wrapper
        -- {ticker, source, scanOrder, record, summary}, verified by the Edge
        -- Function before this service-role-only RPC is reached.
        coalesce(string_agg(record_hash, E'\n' order by source, ticker), ''),
        'sha256'
      ),
      'hex'
    )
  into v_count, v_hash
  from stockscout_private.eod_publish_records
  where upload_id = p_upload_id;

  if v_count <> v_upload.expected_count
     or v_hash <> v_upload.expected_records_hash then
    raise exception 'incomplete or corrupt publish: count %, hash %',
      v_count, v_hash using errcode = '22023';
  end if;

  select id, records_hash into v_existing_scan_id, v_existing_hash
  from public.eod_scans
  where run_id = v_upload.run_id;
  if found then
    if v_existing_hash <> v_hash then
      raise exception 'run id already exists with different content'
        using errcode = '23505';
    end if;
    delete from stockscout_private.eod_publish_uploads
    where id = p_upload_id;
    return jsonb_build_object(
      'scanId', v_existing_scan_id,
      'runId', v_upload.run_id,
      'recordCount', v_count,
      'recordsHash', v_hash,
      'idempotent', true
    );
  end if;

  update stockscout_private.eod_publish_uploads
  set status = 'finalizing', updated_at = now()
  where id = p_upload_id;

  select s.run_id into v_previous_run_id
  from public.eod_scan_state st
  join public.eod_scans s on s.id = st.active_scan_id
  where st.singleton;

  insert into public.eod_scans (
    run_id, scan_date, market_data_date, schema_version, health_status,
    candidate_count, excluded_count, record_count, records_hash,
    manifest_hash, ranking_version, detector_version, health_details,
    provenance, asset_hashes
  ) values (
    v_upload.manifest->>'runId',
    (v_upload.manifest->>'scanDate')::date,
    (v_upload.manifest->>'marketDataDate')::date,
    v_upload.manifest->>'schemaVersion',
    v_upload.manifest#>>'{health,status}',
    (v_upload.manifest#>>'{counts,candidates}')::integer,
    (v_upload.manifest#>>'{counts,excluded}')::integer,
    v_count,
    v_hash,
    v_upload.manifest->>'manifestHash',
    nullif(v_upload.manifest->>'rankingVersion', ''),
    nullif(v_upload.manifest->>'detectorVersion', ''),
    coalesce(v_upload.manifest->'health', '{}'::jsonb),
    coalesce(v_upload.manifest->'provenance', '{}'::jsonb),
    coalesce(v_upload.manifest->'assetHashes', '{}'::jsonb)
  ) returning id into v_scan_id;

  insert into public.eod_candidates (
    scan_id, document_id, ticker, source, scan_order, trade_status,
    primary_setup, risk_level, scan_price, entry_risk_pct, ranking_score,
    record, search_document, record_hash
  )
  select
    v_scan_id,
    'scan:' || v_upload.run_id || ':candidate:' || r.ticker,
    r.ticker,
    r.source,
    r.scan_order,
    coalesce(r.record#>>'{trade_plan,status}', r.record->>'trade_status'),
    coalesce(r.record->>'primary_setup', r.record->>'setup'),
    r.record->>'risk_level',
    case
      when coalesce(r.record->>'scan_price', r.record->>'price', '')
        ~ '^-?[0-9]+([.][0-9]+)?$'
      then coalesce(r.record->>'scan_price', r.record->>'price')::numeric
    end,
    case
      when coalesce(r.record#>>'{trade_plan,entry_risk_pct}', '')
        ~ '^-?[0-9]+([.][0-9]+)?$'
      then (r.record#>>'{trade_plan,entry_risk_pct}')::numeric
    end,
    case
      when coalesce(r.summary->>'rankingScore', r.record->>'headline_score', '')
        ~ '^-?[0-9]+([.][0-9]+)?$'
      then coalesce(r.summary->>'rankingScore', r.record->>'headline_score')::numeric
    end,
    r.record,
    to_tsvector('simple'::regconfig, r.ticker || ' ' || r.record::text),
    r.record_hash
  from stockscout_private.eod_publish_records r
  where r.upload_id = p_upload_id;

  insert into public.eod_candidate_history (
    scan_id, ticker, source, scan_order, trade_status, primary_setup,
    risk_level, scan_price, entry_risk_pct, ranking_score, summary
  )
  select
    c.scan_id, c.ticker, c.source, c.scan_order, c.trade_status,
    c.primary_setup, c.risk_level, c.scan_price, c.entry_risk_pct,
    c.ranking_score,
    jsonb_strip_nulls(r.summary || jsonb_build_object(
      'ticker', c.ticker,
      'source', c.source,
      'scanOrder', c.scan_order,
      'tradeStatus', c.trade_status,
      'primarySetup', c.primary_setup,
      'riskLevel', c.risk_level,
      'scanPrice', c.scan_price,
      'entryRiskPct', c.entry_risk_pct,
      'rankingScore', c.ranking_score
    ))
  from public.eod_candidates c
  join stockscout_private.eod_publish_records r
    on r.upload_id = p_upload_id and r.ticker = c.ticker
  where c.scan_id = v_scan_id;

  insert into public.eod_scan_fields (
    scan_id, field_path, scalar_types, populated_count, example
  )
  select
    v_scan_id,
    field->>'field',
    array(
      select jsonb_array_elements_text(coalesce(field->'types', '[]'::jsonb))
    ),
    case when coalesce(field->>'count', '') ~ '^[0-9]+$'
      then (field->>'count')::integer else 0 end,
    field->'example'
  from jsonb_array_elements(
    coalesce(v_upload.manifest->'fieldCatalog', '[]'::jsonb)
  ) as field
  where coalesce(field->>'field', '')
    ~ '^[A-Za-z0-9_-]+(\.[A-Za-z0-9_-]+)*$'
    and jsonb_typeof(coalesce(field->'types', '[]'::jsonb)) = 'array';

  insert into public.eod_scan_state (singleton, active_scan_id, updated_at)
  values (true, v_scan_id, now())
  on conflict (singleton) do update set
    active_scan_id = excluded.active_scan_id,
    updated_at = excluded.updated_at;

  -- Only the activated scan retains complete records and the field catalog.
  delete from public.eod_candidates where scan_id <> v_scan_id;
  delete from public.eod_scan_fields where scan_id <> v_scan_id;

  -- A rerun replaces the same market session, then history is capped at the
  -- latest 252 sessions. Alert events deliberately keep their textual run id.
  delete from public.eod_scans
  where scan_date = (v_upload.manifest->>'scanDate')::date
    and id <> v_scan_id;
  delete from public.eod_scans
  where id in (
    select id
    from public.eod_scans
    where id <> v_scan_id
    order by scan_date desc, published_at desc, id desc
    offset 251
  );

  delete from stockscout_private.eod_publish_uploads
  where id = p_upload_id;

  return jsonb_build_object(
    'scanId', v_scan_id,
    'runId', v_upload.run_id,
    'recordCount', v_count,
    'recordsHash', v_hash,
    'previousRunId', v_previous_run_id,
    'idempotent', false
  );
end;
$function$;

alter function public.eod_finalize_publish(uuid)
  set statement_timeout = '90s';

create or replace function public.eod_cleanup_abandoned_publish()
returns integer
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_deleted integer;
begin
  delete from stockscout_private.eod_publish_uploads
  where created_at < now() - interval '24 hours';
  get diagnostics v_deleted = row_count;
  return v_deleted;
end;
$function$;

create or replace function public.eod_record_delivery_progress(
  p_user_id uuid,
  p_digest_type text,
  p_session_date date,
  p_content_hash text,
  p_part_count integer,
  p_last_part integer,
  p_completed boolean
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_digest_key text;
  v_row public.eod_delivery_state%rowtype;
begin
  if p_user_id is null or p_session_date is null or p_completed is null
     or p_digest_type is null
     or p_digest_type not in ('daily', 'operational_error')
     or p_content_hash is null
     or p_content_hash !~ '^[0-9a-f]{64}$'
     or p_part_count is null or p_last_part is null
     or p_part_count < 1 or p_part_count > 100
     or p_last_part < 0 or p_last_part > p_part_count
     or (p_completed and p_last_part <> p_part_count) then
    raise exception 'invalid delivery progress' using errcode = '22023';
  end if;
  if not exists (
    select 1 from stockscout_private.eod_owners where user_id = p_user_id
  ) then
    raise exception 'delivery owner is not allowlisted' using errcode = '42501';
  end if;

  v_digest_key := p_digest_type || ':' || p_session_date::text;
  insert into public.eod_delivery_state (
    user_id, channel, digest_key, content_hash, total_parts,
    last_successful_part, completed_at, payload
  ) values (
    p_user_id, 'telegram', v_digest_key, p_content_hash, p_part_count,
    p_last_part, case when p_completed then now() end,
    jsonb_build_object(
      'digestType', p_digest_type,
      'sessionDate', p_session_date::text
    )
  )
  on conflict (user_id, channel, digest_key) do update set
    content_hash = excluded.content_hash,
    total_parts = excluded.total_parts,
    last_successful_part = case
      when eod_delivery_state.content_hash = excluded.content_hash
       and eod_delivery_state.total_parts = excluded.total_parts
      then greatest(
        eod_delivery_state.last_successful_part,
        excluded.last_successful_part
      )
      else excluded.last_successful_part
    end,
    completed_at = case
      when eod_delivery_state.content_hash = excluded.content_hash
       and eod_delivery_state.total_parts = excluded.total_parts
      then coalesce(eod_delivery_state.completed_at, excluded.completed_at)
      else excluded.completed_at
    end,
    payload = excluded.payload,
    updated_at = now()
  returning * into v_row;

  return jsonb_build_object(
    'digestType', p_digest_type,
    'sessionDate', p_session_date::text,
    'contentHash', v_row.content_hash,
    'partCount', v_row.total_parts,
    'lastPart', v_row.last_successful_part,
    'completed', v_row.completed_at is not null,
    'completedAt', v_row.completed_at,
    'updatedAt', v_row.updated_at
  );
end;
$function$;

create or replace function public.eod_get_delivery_state(
  p_user_id uuid,
  p_digest_type text,
  p_session_date date
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_row public.eod_delivery_state%rowtype;
begin
  if p_user_id is null or p_session_date is null or p_digest_type is null
     or p_digest_type not in ('daily', 'operational_error') then
    raise exception 'invalid digest type' using errcode = '22023';
  end if;
  if not exists (
    select 1 from stockscout_private.eod_owners where user_id = p_user_id
  ) then
    raise exception 'delivery owner is not allowlisted' using errcode = '42501';
  end if;

  select * into v_row
  from public.eod_delivery_state
  where user_id = p_user_id
    and channel = 'telegram'
    and digest_key = p_digest_type || ':' || p_session_date::text;

  return jsonb_build_object(
    'digestType', p_digest_type,
    'sessionDate', p_session_date::text,
    'contentHash', v_row.content_hash,
    'partCount', coalesce(v_row.total_parts, 0),
    'lastPart', coalesce(v_row.last_successful_part, 0),
    'completed', v_row.completed_at is not null,
    'completedAt', v_row.completed_at,
    'updatedAt', v_row.updated_at
  );
end;
$function$;

create or replace function public.eod_mark_alert_event_read(p_event_id bigint)
returns boolean
language plpgsql
security invoker
set search_path = ''
as $function$
declare
  v_updated integer;
begin
  update public.eod_alert_events
  set read_at = now()
  where id = p_event_id
    and user_id = (select auth.uid());
  get diagnostics v_updated = row_count;
  return v_updated = 1;
end;
$function$;

revoke all on function
  public.eod_begin_publish(jsonb),
  public.eod_append_publish_chunk(uuid, integer, jsonb),
  public.eod_finalize_publish(uuid),
  public.eod_cleanup_abandoned_publish(),
  public.eod_record_delivery_progress(
    uuid, text, date, text, integer, integer, boolean
  ),
  public.eod_get_delivery_state(uuid, text, date)
from public, anon, authenticated, service_role;
grant execute on function
  public.eod_begin_publish(jsonb),
  public.eod_append_publish_chunk(uuid, integer, jsonb),
  public.eod_finalize_publish(uuid),
  public.eod_cleanup_abandoned_publish(),
  public.eod_record_delivery_progress(
    uuid, text, date, text, integer, integer, boolean
  ),
  public.eod_get_delivery_state(uuid, text, date)
to service_role;

revoke all on function public.eod_mark_alert_event_read(bigint)
  from public, anon, authenticated, service_role;
grant execute on function public.eod_mark_alert_event_read(bigint)
  to authenticated, service_role;

create or replace view public.eod_latest_scan
with (security_invoker = true)
as
select s.*
from public.eod_scan_state st
join public.eod_scans s on s.id = st.active_scan_id
where st.singleton;

create or replace view public.eod_latest_candidates
with (security_invoker = true)
as
select c.*, s.run_id, s.scan_date, s.market_data_date, s.health_status,
  s.published_at
from public.eod_scan_state st
join public.eod_scans s on s.id = st.active_scan_id
join public.eod_candidates c on c.scan_id = s.id
where st.singleton;

create or replace view public.eod_latest_fields
with (security_invoker = true)
as
select f.*, s.run_id, s.scan_date, s.market_data_date, s.health_status,
  s.published_at
from public.eod_scan_state st
join public.eod_scans s on s.id = st.active_scan_id
join public.eod_scan_fields f on f.scan_id = s.id
where st.singleton;

create or replace view public.eod_scan_history
with (security_invoker = true)
as
select s.*, (s.id = st.active_scan_id) as is_active
from public.eod_scans s
left join public.eod_scan_state st on st.singleton;

revoke all on table
  public.eod_latest_scan,
  public.eod_latest_candidates,
  public.eod_latest_fields,
  public.eod_scan_history
from public, anon, authenticated, service_role;
grant select on table
  public.eod_latest_scan,
  public.eod_latest_candidates,
  public.eod_latest_fields,
  public.eod_scan_history
to anon, authenticated, service_role;

-- Private chart payloads contain both daily and weekly OHLCV and are uploaded
-- by the trusted Edge Function as an owner/run manifest plus gzip shards.
insert into storage.buckets (
  id, name, public, file_size_limit, allowed_mime_types
) values (
  'stockscout-eod-charts',
  'stockscout-eod-charts',
  false,
  5242880,
  array['application/json', 'application/gzip']
)
on conflict (id) do update set
  public = false,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy eod_chart_owner_read
on storage.objects
for select
to authenticated
using (
  bucket_id = 'stockscout-eod-charts'
  and (select stockscout_private.eod_is_owner())
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

-- Raw provider cache is private infrastructure, not a public/forkable Actions
-- cache. No anon/authenticated Storage policy is created for this bucket.
insert into storage.buckets (
  id, name, public, file_size_limit, allowed_mime_types
) values (
  'stockscout-eod-market-cache',
  'stockscout-eod-market-cache',
  false,
  52428800,
  array[
    'application/octet-stream',
    'application/gzip',
    'application/x-parquet'
  ]
)
on conflict (id) do update set
  public = false,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
